### ISSUE TITLE
Error: Cannot find module './node_modules/adbkit/lib/adb/client' and TypeError: fns.adapter is not a function

### ISSUE THREAD

**Issue by Thias66** [soef/ioBroker.firetv#13]
**Hardware: Raspberry 3
Standardinstallation (Version 0.0.3.2)
Error while starting the adapter:**

host.ioBroker-Pi | 2017-12-17 15:03:50.772 | error | instance system.adapter.firetv.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2017-12-17 15:03:50.772 | error | by controller[0]: at bootstrap_node.js:496:3
Caught | 2017-12-17 15:03:50.771 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2017-12-17 15:03:50.771 | error | by controller[0]: at run (bootstrap_node.js:383:7)
Caught | 2017-12-17 15:03:50.771 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2017-12-17 15:03:50.770 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2017-12-17 15:03:50.770 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2017-12-17 15:03:50.770 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2017-12-17 15:03:50.769 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2017-12-17 15:03:50.769 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2017-12-17 15:03:50.769 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.firetv/firetv.js:79:20)
Caught | 2017-12-17 15:03:50.768 | error | by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/iobroker.firetv/node_modules/soef/soef.js:1141:23)
Caught | 2017-12-17 15:03:50.767 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2017-12-17 15:03:50.767 | error | by controller[0]: ^
Caught | 2017-12-17 15:03:50.767 | error | by controller[0]: fns.adapter = fns.adapter(options);
Caught | 2017-12-17 15:03:50.766 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.firetv/node_modules/soef/soef.js:1141

**when I change the path in firetv.js to "Client = require('/opt/iobroker/node_modules/adbkit/lib/adb/client')" I get an other error:**

host.ioBroker-Pi | 2017-12-17 15:03:50.772 | error | instance system.adapter.firetv.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2017-12-17 15:03:50.772 | error | by controller[0]: at bootstrap_node.js:496:3
Caught | 2017-12-17 15:03:50.771 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2017-12-17 15:03:50.771 | error | by controller[0]: at run (bootstrap_node.js:383:7)
Caught | 2017-12-17 15:03:50.771 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2017-12-17 15:03:50.770 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2017-12-17 15:03:50.770 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2017-12-17 15:03:50.770 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2017-12-17 15:03:50.769 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2017-12-17 15:03:50.769 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2017-12-17 15:03:50.769 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.firetv/firetv.js:79:20)
Caught | 2017-12-17 15:03:50.768 | error | by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/iobroker.firetv/node_modules/soef/soef.js:1141:23)
Caught | 2017-12-17 15:03:50.767 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2017-12-17 15:03:50.767 | error | by controller[0]: ^
Caught | 2017-12-17 15:03:50.767 | error | by controller[0]: fns.adapter = fns.adapter(options);
Caught | 2017-12-17 15:03:50.766 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.firetv/node_modules/soef/soef.js:1141

Thank you very much for your assistance!

Greetings 
Matthias

**Comment by Thias66** [comment]
ich habe es jetzt doch noch hinbekommen.
Ich musste den Adapter noch einmal neu installieren und somit auch meine Pathanpassung in der firetv.js rückgängig manchen.
Dann folgenden Tipp ausführen:
"Kannst Du einmal von einer Kommandozeile in das ioBroker/node_modules/iobroker.firetv Verzeichnis wechseln und dort dann
npm install
(ohne weiter Parameter) aufrufen. Dann müssten alle für firetv notwendigen Module installiert werden.".

Nun geht es!
